iOS 프로필 이미지, 썸내일 경로, 성별 null로 출력되는 문제 수정
react-native-seoul/react-native-kakao-login pull request #303
Opened 2022-04-29 11:28 UTC by Conradmaker

iOS에서 로그인시 프로필 이미지, 썸내일 경로, 성별이 null로 나오는 이슈에 대한 수정입니다.

2022-05-03 13:15 UTC, JeffGuKang approved these changes
LGTM. 👍

2022-05-15 06:23 UTC, heyman333 approved these changes

2022-05-15 11:25 UTC, jun112465 commented
코드를 수정했음에도 불구하고 여전히 null로 뜹니다. 혹시 다른 원인은 없을까요?

2022-05-15 13:09 UTC, Conradmaker commented
> 
@jun112465 
혹시 다시 빌드하시거나 패키지를 설치하셨는지 한번 확인해보신뒤 실행해 보시는걸 추천드립니다.
그래도 null이 뜨신다면 카카오쪽 셋팅에서 해당정보에 대하여 체크하셨는지 확인후 안되는 값 알려주세요!

2022-05-20 15:46 UTC, hyochan requested changes
PR 감사합니다. 중요한 버그 수정이네요!

리뷰 확인해주시면 감사하겠습니다.

2022-05-20 15:46 UTC, hyochan commented on ios/RNKakaoLogins/RNKakaoLogins.swift
> +                        "thumbnailImageUrl": user?.kakaoAccount?.profile?.thumbnailImageUrl?.absoluteString as Any,
`as Any`를 `as String?`로 바꾸면 어떨까요?

2022-05-20 15:46 UTC, hyochan commented on ios/RNKakaoLogins/RNKakaoLogins.swift
> +                        "gender": user?.kakaoAccount?.gender?.rawValue as Any,
마찬가지입니다.

2022-05-21 03:41 UTC, hyochan approved these changes
다른 파라미터의 typecast도 문제가 있기 때문에 우선은 머지하겠습니다 :)

다음 `PR`에 `typecast` 문제를 한번에 해결해야할 것 같습니다.

감사합니다.

2022-05-21 03:41 UTC, merged

2022-05-21 07:12 UTC, Conradmaker commented
감사합니다 :)