Refactor build configs (build.gradle, Podfile)
react-native-seoul/react-native-kakao-login pull request #305
Opened 2022-05-20 13:01 UTC by WoonHaKim

## AS-IS

기존에 쓰고 있는 다른 라이브러리의 kakao sdk나 build tool (ex. gradle tools) 의 버전과 mismatch 되어 빌드에 문제 발생.

## Solution

- [create-react-native-library](https://github.com/callstack/react-native-builder-bob/tree/main/packages/create-react-native-library/templates) 의 템플릿을 참고로 하여 root project의 `kotlinVersion`, `compileSdkVersion`, `targetSdkVersion`, `gradleVersion` 등을 우선적으로 바라보도록 `build.gradle` 수정
- [RNFirebase의 서브 프로젝트](https://github.com/invertase/react-native-firebase/tree/main/packages) Podfile 버전 참조 방식을 참고로 하여, Podfile에 `$KakaoSDKVersion` 추가 및 `package.json`에 지정된 값을 먼저 가져오도록 수정

## TO-BE

1. Android: rootProject의 환경변수를 먼저 가져오고 fallback으로 `gradle.properties`에 지정된 값을 기본값으로 사용.
2. iOS: package.json에 설정된 `sdkVersions.ios.kakao` 의 버전을 기본으로 가져오되, `$KakaoSDKVersion`이 `Podfile`에 지정된 경우 이를 우선 사용 함. (`$KakaoSDKVersion`은 호환성을 체크하고 신중히 사용 하셔야 합니다.)
3. kakaoSDKs version: 2.9.0 -> 2.9.1 bump

2022-05-20 13:02 UTC, WoonHaKim commented
closes #304

2022-05-20 15:51 UTC, hyochan requested changes
훌륭한 `PR` 감사드립니다.

소소한 리뷰 확인 부탁드립니다 :pray:

2022-05-20 15:51 UTC, hyochan commented on android/build.gradle
> +    jcenter()
이걸 삭제해줘도 빌드에 문제가 없으면 삭제해주시면 좋을 것 같아요.
https://github.com/react-native-community/discussions-and-proposals/issues/331

2022-05-20 15:51 UTC, hyochan commented on KakaoLoginExample/ios/Podfile
> +# $KakaoSDKVersion = "2.9.0"
라이브러리 호환성을 위해서 `default`로 설정을 해주는게 좋지 않을까요?

2022-05-20 16:27 UTC, WoonHaKim commented on KakaoLoginExample/ios/Podfile
> +# $KakaoSDKVersion = "2.9.0"
테스트를 위한 코맨트가 남아있었군요. kakao-login.podspec의 `kakao_sdk_version`을 기본으로 사용하도록 수정되었습니다.
2.9.1에서 별 문제는 없었으나, 만약의 호환성을 위해 sdk버전이 2.9.0로 롤백되었습니다. 감사합니다.

2022-05-21 03:37 UTC, hyochan approved these changes
고생하셨습니다 🙏

2022-05-21 03:37 UTC, merged