refactor: extract logic by platforms using interface
react-native-seoul/react-native-kakao-login pull request #345
Opened 2022-11-04 08:15 UTC by bang9

2022-11-06 13:08 UTC, YangJonghun commented
시간내서 PR만들어주셔서 감사합니다! 바빠서 이슈만 만들어놓고 제가 고칠생각을 못했네요🥲
Issue #337 에서 제기됐던 문제는 해결 되었습니다! 정말 감사해요🙇‍♂️
제가 메인테이너는 아니지만 작성해주신 코드를 살짝 리뷰해봤는데 추가되면 좋을 것 같은 내용들을 몇 가지 적었습니다.

1. 아래와 같은 코드를 사용하고 계실 분들을 위해 src/index.ts에서 src/types/index.ts를 re-exports할 필요가 있을 것 같습니다.
```
import type { KakaoOAuthToken } from '@react-native-seoul/kakao-login'
```

2. 현재코드들은 사용하는 쪽에서 `tsconfig.json`의 `compilerOptions.moduleSuffixes`등을 별도로 설정해도 타입시스템에선 접근이 가능한 상태인 것으로 보입니다.(제가 뭔가 설정을 잘못했을지도 모르니 추가설정이 필요하다면 알려주세요!)
작성해주신 코드로 봤을 때 런타임에 분명 에러가 날테고 명시적으로 parameter이름에 `web`등이 적혀있어서 사용자 쪽에서 실수할 여지는 적을 것 같은데 이왕이면 타입에서도 web/native분기가 되면 좋을 것 같다는 생각이 들어서 조금 적었습니다.

2022-11-08 02:48 UTC, bang9 commented
> 시간내서 PR만들어주셔서 감사합니다! 바빠서 이슈만 만들어놓고 제가 고칠생각을 못했네요🥲 제가 사용해봤을 때 Issue #337 에서 제기됐던 문제는 해결 되었습니다! 정말 감사해요🙇‍♂️ 작성해주신 코드를 살짝 리뷰해봤는데 아래와 같은 코드를 사용하고 계실 분들을 위해 src/index.ts에서 src/types/index.ts를 re-exports할 필요가 있을 것 같습니다.
> 
> ```
> import type { KakaoOAuthToken } from '@react-native-seoul/kakao-login'
> ```

리뷰해주셔서 감사합니다 :) re-exports 는 놓친 부분이었는데 감사합니다.
module suffixes 를 설정해보았는데요! 설정된 순서대로 컴파일 시점에 파일참조 우선순위를 정하는 옵션이다보니
에디터에서도 moduleSuffixes 에 설정된 순서로 파일이 결정되고, native/web 의 tsconfig 가 분리되지 않은 프로젝트일 경우
모듈의 한쪽 타입만 참조하게되는 문제가 생기는거 같습니다. (moduleSuffixes 에 web 을 우선순위 높게 설정하면, native 에서도 web 모듈 타입만을 참조)
언제 작업이 될지는 모르겠지만, 근본적인 문제인 인터페이스를 통일하는게 제일 좋은방법이지 않을까 합니다!

2022-11-26 04:27 UTC, hyochan commented on package.json
> +  "main": "src/index",
오우... 이전에 #325 에서 `native.js`파일을 분류하였다가 인식문제가 있어 다시 병합하였습니다.
이렇게 하면 파일을 분류해도 인식을 잘 하나 보네요.

감사합니다.

@nain93 시간 되실 때 내용 확인해주시면 좋을 것 같습니다.

2022-11-26 04:27 UTC, hyochan requested changes
PR 좋아보입니다. 감사합니다 🙏

2022-11-26 04:27 UTC, hyochan approved these changes

2022-11-26 04:28 UTC, merged