feat: kakao login scopes
react-native-seoul/react-native-kakao-login pull request #411
Opened 2024-07-08 10:56 UTC by nnnnoel

https://developers.kakao.com/docs/latest/ko/kakaologin/ios#additional-feature

2024-08-20 12:06 UTC, hyochan requested changes
안녕하세요! PR 감사드립니다.
불필요한 띄어쓰기만 우선 제거해주시면 매우 감사하겠습니다!!

2024-08-20 12:06 UTC, hyochan commented on ios/RNKakaoLogins/RNKakaoLogins.swift
> +
불필요한 띄어쓰기를 되돌려 주시면 감사하겠습니다.

2024-08-20 12:06 UTC, hyochan commented on ios/RNKakaoLogins/RNKakaoLogins.swift
> +                rejecter reject: @escaping RCTPromiseRejectBlock) -> Void {
여기도요!

2026-03-02 11:18 UTC, nnnnoel commented
안녕하세요, @hyochan 님.
답변이 많이 늦었습니다.
업무가 바빠지면서 해당 PR을 메인터넌스 하지 못 할 것 같아 이만 close 하도록 하겠습니다.

2026-03-02 11:18 UTC, closed without merging